# Generated by Django 3.2.17 on 2023-02-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='burn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('director', 'директор'), ('manager', 'управляющий'), ('accounter', 'бухгалтер'), ('electrician', 'электрик'), ('plumber', 'сантехник'), ('locksmith', 'слесарь')], max_length=200, null=True),
        ),
    ]
