# Generated by Django 3.2.17 on 2023-03-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230305_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('statistic_permission', models.BooleanField(default=True)),
                ('fund_permission', models.BooleanField(default=False)),
                ('receipt_permission', models.BooleanField(default=False)),
                ('accounts_permission', models.BooleanField(default=False)),
                ('appartments_permission', models.BooleanField(default=False)),
                ('owners_permission', models.BooleanField(default=False)),
                ('house_permission', models.BooleanField(default=True)),
                ('messages_permission', models.BooleanField(default=False)),
                ('masters_request_permission', models.BooleanField(default=True)),
                ('counter_permission', models.BooleanField(default=False)),
                ('site_managing_permission', models.BooleanField(default=False)),
                ('utility_services_permission', models.BooleanField(default=False)),
                ('tarif_permission', models.BooleanField(default=False)),
                ('role_section_permission', models.BooleanField(default=False)),
                ('users_sections_permission', models.BooleanField(default=False)),
                ('requisite_sections_permission', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='telegam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='viber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role'),
        ),
    ]
