# Generated by Django 3.2.17 on 2023-03-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='accounts_permission',
            field=models.BooleanField(default=False, verbose_name='лицевые счета'),
        ),
        migrations.AlterField(
            model_name='role',
            name='appartments_permission',
            field=models.BooleanField(default=False, verbose_name='квартиры'),
        ),
        migrations.AlterField(
            model_name='role',
            name='counter_permission',
            field=models.BooleanField(default=False, verbose_name='счетчики'),
        ),
        migrations.AlterField(
            model_name='role',
            name='fund_permission',
            field=models.BooleanField(default=False, verbose_name='касса'),
        ),
        migrations.AlterField(
            model_name='role',
            name='house_permission',
            field=models.BooleanField(default=True, verbose_name='дома'),
        ),
        migrations.AlterField(
            model_name='role',
            name='masters_request_permission',
            field=models.BooleanField(default=True, verbose_name='заявки вызова мастера'),
        ),
        migrations.AlterField(
            model_name='role',
            name='messages_permission',
            field=models.BooleanField(default=False, verbose_name='сообщения'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='role',
            name='owners_permission',
            field=models.BooleanField(default=False, verbose_name='владельцы квартир'),
        ),
        migrations.AlterField(
            model_name='role',
            name='receipt_permission',
            field=models.BooleanField(default=False, verbose_name='квитанции на оплату'),
        ),
        migrations.AlterField(
            model_name='role',
            name='requisite_sections_permission',
            field=models.BooleanField(default=False, verbose_name='платежные реквизиты'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_section_permission',
            field=models.BooleanField(default=False, verbose_name='роли'),
        ),
        migrations.AlterField(
            model_name='role',
            name='site_managing_permission',
            field=models.BooleanField(default=False, verbose_name='управление сайтом'),
        ),
        migrations.AlterField(
            model_name='role',
            name='statistic_permission',
            field=models.BooleanField(default=True, verbose_name='статистика'),
        ),
        migrations.AlterField(
            model_name='role',
            name='tarif_permission',
            field=models.BooleanField(default=False, verbose_name='тарифы'),
        ),
        migrations.AlterField(
            model_name='role',
            name='users_sections_permission',
            field=models.BooleanField(default=False, verbose_name='пользователи'),
        ),
        migrations.AlterField(
            model_name='role',
            name='utility_services_permission',
            field=models.BooleanField(default=False, verbose_name='услуги'),
        ),
    ]
