# Generated by Django 3.2.17 on 2023-04-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telegam',
            new_name='telegram',
        ),
    ]
