# Generated by Django 3.2.17 on 2023-05-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_telegam_user_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetouser',
            name='message_target_type',
            field=models.CharField(choices=[('one_user', 'один пользователь'), ('all_users_per_house', 'по домам'), ('all_users_per_floor', 'по этажам'), ('all_users_per_sections', 'по секциям'), ('all_users', 'все пользователи')], default='one_user', max_length=200),
        ),
    ]
