# Generated by Django 3.2.17 on 2023-05-19 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_messagetouser_message_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetouser',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagetouser',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
