# Generated by Django 3.2.17 on 2023-05-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230519_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetouser',
            name='message_target_type',
            field=models.CharField(choices=[('one_user', 'один пользователь'), ('all_users_per_house', 'по домам'), ('all_users_per_floor', 'по этажам'), ('all_users_per_sections', 'по секциям'), ('all_users', 'все пользователи')], default='all_users', max_length=200),
        ),
    ]
