# Generated by Django 3.2.17 on 2023-06-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_messagetouser_message_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetouser',
            name='read_by_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
