# Generated by Django 3.2.17 on 2023-06-06 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_messagetouser_read_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetouser',
            name='read_by_user',
        ),
        migrations.AddField(
            model_name='messagetouser',
            name='read_by_user',
            field=models.ManyToManyField(related_name='readed_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
