version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/MyHouse24/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    


  db:
    image: postgres:15.3-alpine
    # container_name: home_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev


  redis:
    image: redis:alpine


  celery:
    restart: always
    build:
      context: .
    command: celery -A MyHouse24_proj worker -l info
    volumes:
      - ./:/usr/src/MyHouse24/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web


volumes:
  postgres_data:
