version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      # cache_from:
      #   - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: gunicorn MyHouse24_proj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/MyHouse24/web/staticfiles
      - media_volume:/home/MyHouse24/web/media
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    


  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # env_file:
    #   - ./.env.prod.db
    env_file:
      - ./.env.prod


  redis:
    image: redis:alpine


  celery:
    restart: always
    build:
      context: .
    command: celery -A MyHouse24_proj worker -l info
    volumes:
      - ./:/usr/src/MyHouse24/
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
      - web

  nginx:
    build: ./nginx
    # cache_from:
    #   - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/MyHouse24/web/staticfiles
      - media_volume:/home/MyHouse24/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: