# Generated by Django 3.2.17 on 2023-02-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('keyword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_descriptions', models.TextField()),
                ('show_app_link', models.BooleanField()),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('simple_text', models.TextField()),
                ('url', models.URLField()),
                ('full_name', models.CharField(max_length=400)),
                ('location', models.TextField()),
                ('address', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=400)),
                ('link_to_commercial_cite', models.URLField(max_length=400)),
                ('map_code', models.TextField()),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('director_photo', models.ImageField(blank=True, upload_to='galery/', verbose_name='Фото директора')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.seoblock')),
            ],
        ),
    ]
