# Generated by Django 3.2.17 on 2023-06-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document/', verbose_name='Файл')),
                ('target', models.CharField(choices=[('about_us', 'о нас')], max_length=200)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('keyword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SlideBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='galery/', verbose_name='фото')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('target', models.CharField(choices=[('main_page_slider', 'Главная страница слайдер'), ('main_page_around', 'Главная страница рядом с нами'), ('about_us_galery', 'О нас, галерея'), ('about_us_addition_galery', 'О нас, дополнительная галерея'), ('services', 'Услуги'), ('tariff', 'Тариф')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TariffPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('seo_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_descriptions', models.TextField()),
                ('show_app_link', models.BooleanField()),
                ('seo_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_page', to='website.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('simple_text', models.TextField()),
                ('full_name', models.CharField(max_length=400)),
                ('location', models.TextField()),
                ('address', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=400)),
                ('link_to_commercial_cite', models.URLField(max_length=400)),
                ('map_code', models.TextField()),
                ('seo_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('director_photo', models.ImageField(blank=True, upload_to='galery/', verbose_name='Фото директора')),
                ('addition_title', models.CharField(blank=True, max_length=200, null=True)),
                ('addition_short_description', models.TextField(blank=True, null=True)),
                ('seo_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.seoblock')),
            ],
        ),
    ]
