# Generated by Django 3.2.17 on 2023-05-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_mainpage_seo_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideblock',
            name='target',
            field=models.CharField(choices=[('main_page_slider', 'Главная страница слайдер'), ('main_page_around', 'Главная страница рядом с нами'), ('about_us_galery', 'О нас, галерея'), ('services', 'Услуги')], default='title', max_length=200),
            preserve_default=False,
        ),
    ]
