# Generated by Django 3.2.17 on 2023-05-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_slideblock_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='seo_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_page', to='website.seoblock'),
        ),
    ]
