# Generated by Django 3.2.17 on 2023-05-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20230524_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='seo_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.seoblock'),
        ),
    ]
