# Generated by Django 3.2.17 on 2023-05-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoblock',
            name='image',
            field=models.ImageField(blank=True, upload_to='galery/', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
