# Generated by Django 3.2.17 on 2023-05-28 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20230526_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoblock',
            name='image',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='title',
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='seo_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.seoblock'),
        ),
    ]
