# Generated by Django 3.2.17 on 2023-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20230528_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideblock',
            name='target',
            field=models.CharField(choices=[('main_page_slider', 'Главная страница слайдер'), ('main_page_around', 'Главная страница рядом с нами'), ('about_us_galery', 'О нас, галерея'), ('about_us_addition_galery', 'О нас, дополнительная галерея'), ('services', 'Услуги'), ('tariff', 'Тариф')], max_length=200),
        ),
    ]
