# Generated by Django 3.2.17 on 2023-05-28 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_tariffpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffpage',
            name='seo_block',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.seoblock'),
            preserve_default=False,
        ),
    ]
