# Generated by Django 3.2.17 on 2023-05-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_tariffpage_seo_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffpage',
            name='seo_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.seoblock'),
        ),
    ]
