# Generated by Django 3.2.17 on 2023-06-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastersRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_type', models.CharField(choices=[('electrician', 'электрик'), ('plumber', 'сантехник'), ('locksmith', 'слесарь'), ('any_specialist', 'любой специалист')], max_length=200)),
                ('date_work', models.DateField()),
                ('time_work', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'новая'), ('is_performing', 'в работе'), ('have_done', 'выполнена')], max_length=200)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('appartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartments.appartment')),
            ],
        ),
    ]
