# Generated by Django 3.2.17 on 2023-05-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters_services', '0003_alter_mastersrequest_master_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersrequest',
            name='status',
            field=models.CharField(choices=[('new', 'новая'), ('is_performing', 'в работе'), ('have_done', 'выполнена')], max_length=200),
        ),
    ]
