# Generated by Django 3.2.17 on 2023-05-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters_services', '0004_alter_mastersrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastersrequest',
            old_name='desctiption',
            new_name='description',
        ),
    ]
