# Generated by Django 3.2.17 on 2023-06-07 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters_services', '0006_alter_mastersrequest_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersrequest',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastersrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastersrequest',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masters_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
