# Generated by Django 3.2.17 on 2023-02-21 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('appartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartments.appartment')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('updated_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('appartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartments.appartment')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_services.unitofmeasure')),
            ],
        ),
        migrations.CreateModel(
            name='TariffCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('description', models.TextField()),
                ('updated_datetime', models.DateTimeField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('curency', models.CharField(max_length=200)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_services.tariff')),
                ('utility_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_services.utilityservice')),
            ],
        ),
        migrations.CreateModel(
            name='CounterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('zero', 'Нулевое'), ('new', 'Новое'), ('taken_into_account', 'Учтено'), ('taken_into_account_and_paid', 'Учтено и оплачено')], max_length=200)),
                ('date', models.DateField()),
                ('readings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_services.counter')),
            ],
        ),
        migrations.AddField(
            model_name='counter',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_services.unitofmeasure'),
        ),
    ]
