# Generated by Django 3.2.17 on 2023-06-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shown_in_counters', models.BooleanField(default=False)),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility_services.unitofmeasure')),
            ],
        ),
        migrations.CreateModel(
            name='TariffCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(blank=True, null=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('curency', models.CharField(default='грн', max_length=200)),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility_services.tariff')),
                ('utility_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_service_tariff_cell', to='utility_services.utilityservice')),
            ],
        ),
        migrations.CreateModel(
            name='CounterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('zero', 'Нулевое'), ('new', 'Новое'), ('taken_into_account', 'Учтено'), ('taken_into_account_and_paid', 'Учтено и оплачено')], max_length=200)),
                ('date', models.DateField()),
                ('readings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('appartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_readings_appartment', to='appartments.appartment')),
                ('utility_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_reading', to='utility_services.utilityservice')),
            ],
        ),
    ]
