# Generated by Django 3.2.17 on 2023-03-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0010_alter_appartment_owner_user'),
        ('utility_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='appartments',
            field=models.ManyToManyField(related_name='tariff', to='appartments.Appartment', verbose_name='квартиры'),
        ),
    ]
