# Generated by Django 3.2.17 on 2023-04-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0003_auto_20230403_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilityservice',
            name='shown_in_counters',
            field=models.BooleanField(default=False),
        ),
    ]
