# Generated by Django 3.2.17 on 2023-04-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0012_alter_appartment_personal_account'),
        ('utility_services', '0004_utilityservice_shown_in_counters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffcell',
            name='description',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='appartments',
            field=models.ManyToManyField(blank=True, null=True, related_name='tariff', to='appartments.Appartment', verbose_name='квартиры'),
        ),
    ]
