# Generated by Django 3.2.17 on 2023-04-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0005_auto_20230404_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffcell',
            name='number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
