# Generated by Django 3.2.17 on 2023-04-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0006_alter_tariffcell_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffcell',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
