# Generated by Django 3.2.17 on 2023-04-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0008_alter_tariffcell_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
