# Generated by Django 3.2.17 on 2023-04-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0009_alter_tariff_updated_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffcell',
            name='curency',
            field=models.CharField(default='грн', max_length=200),
        ),
    ]
