# Generated by Django 3.2.17 on 2023-04-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0010_alter_tariffcell_curency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterreadings',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_reading', to='utility_services.counter'),
        ),
    ]
