# Generated by Django 3.2.17 on 2023-04-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0013_auto_20230414_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterreadings',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
