# Generated by Django 3.2.17 on 2023-04-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0014_alter_counterreadings_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='appartments',
        ),
    ]
