# Generated by Django 3.2.17 on 2023-04-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0015_remove_tariff_appartments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffcell',
            name='utility_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_service_tariff_cell', to='utility_services.utilityservice'),
        ),
    ]
