# Generated by Django 3.2.17 on 2023-04-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0016_alter_tariffcell_utility_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='title',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='utilityservice',
            name='appartment',
        ),
    ]
