# Generated by Django 3.2.17 on 2023-04-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0017_auto_20230424_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='utility_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility_services.utilityservice'),
        ),
    ]
