# Generated by Django 3.2.17 on 2023-04-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0013_appartment_tariff'),
        ('utility_services', '0019_auto_20230425_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilityservice',
            name='appartment',
        ),
        migrations.AddField(
            model_name='counterreadings',
            name='appartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appartments.appartment'),
        ),
    ]
