# Generated by Django 3.2.17 on 2023-04-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0013_appartment_tariff'),
        ('utility_services', '0020_auto_20230425_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterreadings',
            name='appartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_readings_appartment', to='appartments.appartment'),
        ),
    ]
