# Generated by Django 3.2.17 on 2023-06-23 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility_services', '0001_initial'),
        ('appartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid_for', 'Оплачена'), ('partly', 'Частично'), ('unpaid', 'Неоплачена')], max_length=200)),
                ('number', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('from_date', models.DateField(default=datetime.date(2023, 6, 9))),
                ('to_date', models.DateField(default=datetime.date(2023, 6, 23))),
                ('payment_due', models.DateField()),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_was_made', models.BooleanField(default=False)),
                ('appartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appartments.appartment')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility_services.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_cells', to='receipts.receipt')),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility_services.unitofmeasure')),
                ('utility_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility_services.utilityservice')),
            ],
        ),
    ]
