# Generated by Django 3.2.17 on 2023-02-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility_services', '0001_initial'),
        ('appartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid_for', 'Оплачена'), ('partly', 'Частично'), ('unpaid', 'Неоплачена')], max_length=200)),
                ('from_data', models.TextField()),
                ('to_data', models.TextField()),
                ('payment_due', models.DateField()),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_was_made', models.BooleanField(default=False)),
                ('appartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartments.appartment')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartments.personalaccount')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_services.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('receipt_template', models.FileField(blank=True, upload_to='mailing_templates/')),
            ],
        ),
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counter_readings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utility_services.counterreadings')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt')),
                ('utility_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_services.utilityservice')),
            ],
        ),
    ]
