# Generated by Django 3.2.17 on 2023-04-18 11:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0013_appartment_tariff'),
        ('utility_services', '0015_remove_tariff_appartments'),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='from_data',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='tariff',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='to_data',
        ),
        migrations.AddField(
            model_name='receipt',
            name='from_date',
            field=models.DateField(default=datetime.date(2023, 4, 4)),
        ),
        migrations.AddField(
            model_name='receipt',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='to_date',
            field=models.DateField(default=datetime.date(2023, 4, 18)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='appartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appartments.appartment'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appartments.personalaccount'),
        ),
        migrations.AlterField(
            model_name='receiptcell',
            name='counter_readings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility_services.counterreadings'),
        ),
        migrations.AlterField(
            model_name='receiptcell',
            name='utility_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility_services.utilityservice'),
        ),
    ]
