# Generated by Django 3.2.17 on 2023-04-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_auto_20230418_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='personal_account',
        ),
    ]
