# Generated by Django 3.2.17 on 2023-04-19 10:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0015_remove_tariff_appartments'),
        ('receipts', '0003_remove_receipt_personal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility_services.tariff'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='from_date',
            field=models.DateField(default=datetime.date(2023, 4, 5)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='to_date',
            field=models.DateField(default=datetime.date(2023, 4, 19)),
        ),
    ]
