# Generated by Django 3.2.17 on 2023-04-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0015_remove_tariff_appartments'),
        ('receipts', '0005_auto_20230422_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptcell',
            name='counter_readings',
        ),
        migrations.RemoveField(
            model_name='receiptcell',
            name='utility_service',
        ),
        migrations.AddField(
            model_name='receiptcell',
            name='consumption',
            field=models.DecimalField(decimal_places=2, default=11.11, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiptcell',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility_services.unitofmeasure'),
        ),
    ]
