# Generated by Django 3.2.17 on 2023-04-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0015_remove_tariff_appartments'),
        ('receipts', '0006_auto_20230422_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcell',
            name='utility_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility_services.utilityservice'),
        ),
        migrations.AlterField(
            model_name='receiptcell',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt'),
        ),
    ]
