# Generated by Django 3.2.17 on 2023-04-25 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0008_auto_20230424_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='from_date',
            field=models.DateField(default=datetime.date(2023, 4, 11)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='to_date',
            field=models.DateField(default=datetime.date(2023, 4, 25)),
        ),
    ]
