# Generated by Django 3.2.17 on 2023-04-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0010_auto_20230430_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptcell',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_cells', to='receipts.receipt'),
        ),
    ]
