# Generated by Django 3.2.17 on 2023-04-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0011_alter_receiptcell_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipttemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
