# Generated by Django 3.2.17 on 2023-05-16 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0015_auto_20230515_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='from_date',
            field=models.DateField(default=datetime.date(2023, 5, 2)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='to_date',
            field=models.DateField(default=datetime.date(2023, 5, 16)),
        ),
    ]
