# Generated by Django 3.2.17 on 2023-05-19 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0016_auto_20230516_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='from_date',
            field=models.DateField(default=datetime.date(2023, 5, 5)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='to_date',
            field=models.DateField(default=datetime.date(2023, 5, 19)),
        ),
    ]
