# Generated by Django 3.2.17 on 2023-06-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('arrive', 'приходная'), ('expense', 'расходная')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(unique=True)),
                ('date', models.DateField()),
                ('type_of_statement', models.CharField(choices=[('arrival', 'Приход'), ('expense', 'Расход')], max_length=200)),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checked', models.BooleanField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
