# Generated by Django 3.2.17 on 2023-02-21 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checked', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('arrive', 'приходная'), ('expense', 'расходная')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checked', models.BooleanField()),
                ('comment', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.item')),
            ],
        ),
    ]
