# Generated by Django 3.2.17 on 2023-06-23 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appartments', '0002_initial'),
        ('receipts', '0001_initial'),
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statement',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appartments.personalaccount'),
        ),
        migrations.AddField(
            model_name='statement',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipts.receipt'),
        ),
        migrations.AddField(
            model_name='statement',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility_services.tariff'),
        ),
        migrations.AddField(
            model_name='statement',
            name='type_of_paynent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statements.paymentitem'),
        ),
    ]
