# Generated by Django 3.2.17 on 2023-05-08 12:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0013_auto_20230508_1240'),
        ('appartments', '0013_appartment_tariff'),
        ('utility_services', '0021_alter_counterreadings_appartment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statements', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(unique=True)),
                ('date', models.DateField(default=datetime.datetime(2023, 5, 8, 12, 39, 57, 299460, tzinfo=utc))),
                ('checked_status', models.BooleanField()),
                ('type_of_statement', models.CharField(choices=[('arrival', 'Приход'), ('expense', 'Расход')], max_length=200)),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checked', models.BooleanField()),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personal_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appartments.personalaccount')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipts.receipt')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility_services.tariff')),
            ],
        ),
        migrations.RemoveField(
            model_name='expensestatement',
            name='item',
        ),
        migrations.RemoveField(
            model_name='expensestatement',
            name='manager',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='PaymentItem',
        ),
        migrations.DeleteModel(
            name='ArrivalStatement',
        ),
        migrations.DeleteModel(
            name='ExpenseStatement',
        ),
        migrations.AddField(
            model_name='statement',
            name='type_of_paynent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statements.paymentitem'),
        ),
    ]
