# Generated by Django 3.2.17 on 2023-05-09 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_auto_20230508_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 9, 11, 2, 33, 903909, tzinfo=utc)),
        ),
    ]
