# Generated by Django 3.2.17 on 2023-05-09 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0004_auto_20230509_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 9, 11, 47, 44, 338506, tzinfo=utc)),
        ),
    ]
