# Generated by Django 3.2.17 on 2023-05-09 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0005_alter_statement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='checked_status',
        ),
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 9, 13, 4, 46, 803664, tzinfo=utc)),
        ),
    ]
