# Generated by Django 3.2.17 on 2023-05-15 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0006_auto_20230509_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 12, 39, 40, 243032, tzinfo=utc)),
        ),
    ]
