# Generated by Django 3.2.17 on 2023-06-06 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0038_alter_statement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 10, 38, 39, 639348, tzinfo=utc)),
        ),
    ]
