# Generated by Django 3.2.17 on 2023-06-23 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='responsibilities',
            field=models.ManyToManyField(related_name='responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='Обязанности'),
        ),
        migrations.AddField(
            model_name='floor',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='appartments.house'),
        ),
        migrations.AddField(
            model_name='appartment',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_appartment', to='appartments.floor'),
        ),
        migrations.AddField(
            model_name='appartment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_appartment', to='appartments.house'),
        ),
        migrations.AddField(
            model_name='appartment',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owning', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appartment',
            name='personal_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appartment_account', to='appartments.personalaccount'),
        ),
        migrations.AddField(
            model_name='appartment',
            name='sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_appartment', to='appartments.section'),
        ),
        migrations.AddField(
            model_name='appartment',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appartment_tariff', to='utility_services.tariff', verbose_name='тариф'),
        ),
    ]
