# Generated by Django 3.2.17 on 2023-03-08 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='galery/', verbose_name='Изображения'),
        ),
        migrations.CreateModel(
            name='HouseAdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galery/', verbose_name='Изображения')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartments.house')),
            ],
        ),
    ]
