# Generated by Django 3.2.17 on 2023-03-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0003_auto_20230308_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='section',
            name='main_image',
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название дома'),
        ),
    ]
