# Generated by Django 3.2.17 on 2023-03-12 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appartments', '0005_house_responsibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='responsibilities',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='обязанности'),
        ),
    ]
