# Generated by Django 3.2.17 on 2023-03-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0007_alter_house_responsibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseadditionalimage',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addition_images', to='appartments.house'),
        ),
    ]
