# Generated by Django 3.2.17 on 2023-03-17 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appartments', '0008_alter_houseadditionalimage_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalaccount',
            name='appartment',
        ),
        migrations.AlterField(
            model_name='appartment',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appartment',
            name='personal_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_account', to='appartments.personalaccount'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='appartments.house'),
        ),
        migrations.AlterField(
            model_name='house',
            name='responsibilities',
            field=models.ManyToManyField(related_name='responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='section',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='appartments.house'),
        ),
    ]
