# Generated by Django 3.2.17 on 2023-03-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0010_alter_appartment_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartment',
            name='balance',
        ),
    ]
