# Generated by Django 3.2.17 on 2023-03-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0011_remove_appartment_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='personal_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appartment_account', to='appartments.personalaccount'),
        ),
    ]
