# Generated by Django 3.2.17 on 2023-05-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0013_appartment_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
