# Generated by Django 3.2.17 on 2023-05-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0014_alter_personalaccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor', to='appartments.floor'),
        ),
        migrations.AlterField(
            model_name='appartment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='appartments.house'),
        ),
        migrations.AlterField(
            model_name='appartment',
            name='sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='appartments.section'),
        ),
    ]
