# Generated by Django 3.2.17 on 2023-02-21 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appartments', '0001_initial'),
        ('utility_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphIncomeExpendCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DurationField()),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_expend', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GraphPayOffReceiptCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DurationField()),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid_off', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GraphTotalStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fund_state', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SumPerAppartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartments.appartment')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousMounthExchangeCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_month_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartments.appartment')),
                ('utility_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_services.utilityservice')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangePerMounthThisYearCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_per_month_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartments.appartment')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentYearExchengeCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year_exchange_summ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartments.appartment')),
                ('utility_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_services.utilityservice')),
            ],
        ),
    ]
